#pragma once

#include "NativeGameplayTags.h"

namespace A1GameplayTags
{
	// InitState
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	// Input
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Left);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Right);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Confirm);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Cancel);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_UseItem);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Skill_1);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Skill_2);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Widget_Inventory);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Widget_SkinSelection);
	
	// Ability
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Crouch);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Death);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Knockback);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Stun);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Check);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Active);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint_Check);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint_Active);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChangeEquip);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_1);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_2);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_3);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Bow);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Skill);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Skill_1);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Skill_2);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Throw);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Drink);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Block);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS_Bow);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS_Throw);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Active);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Object);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_FlashLight);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_DropItem);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Widget_Inventory);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Widget_WorldMap);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Widget_SkinSelection);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HitReact);

	// Status
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouch);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Jump);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Knockback);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stun);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Attack);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Skill);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Throw);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Drink);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Block);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ChangeEquip);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS_Bow);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS_Ready);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS_Throw);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dash);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Sprint);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Succeeded);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Failed);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Interact);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_HitReact);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_RejectHitReact);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_StaminaRecoveryBlock);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_PiercingShot);

	// Gameplay Event
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Begin);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Tick);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_End);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Spell);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Play);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Trace);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_CameraShake);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ChangeEquip);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ArrowVisibility);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Potion_Drink);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Potion_Fill);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Knockback);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Stun);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Bow_ADS);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_HitReact);
	
	// Cheat
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);
	
	// Movement
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	// Message
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Notification);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Notice);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Progress);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_MyInventory);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_OtherInventory);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_MyEquipment);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_OtherEquipment);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HUD_Spell_Input);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HUD_Spell_Progress_Construct);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HUD_Spell_Progress_Refresh);

	// SetByCaller
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseDamage);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseHealth);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseMana);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseStamina);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingDamage);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingHealth);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingMana);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingStamina);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeed);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeedPercent);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Strength);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Defense);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Vigor);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Agility);
	A1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Resourcefulness);

	// GameplayCue
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Attack);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Impact);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Cast_Fireball);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Cast_Skill);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill_Targeting_Burst);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill_Targeting_Loop);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Overlay);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Loop);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Success);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Fail);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Skill_Buff);

	// Cooldown
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Bow_Fire);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Jump);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dash);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Statue);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Sprint);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_1);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_2);

	// GamePhase
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_PreGame);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_Game);
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_PostGame);

	// HUD
	A1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Slot_Reticle);
	
	A1GAME_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	A1GAME_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;
	
	A1GAME_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
};
