// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace LyraGameplayTags
{
	// InitState
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	// Input
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Primary);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Secondary);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Tertiary);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Quaternary);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Quinary);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Senary);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Confirm);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Cancel);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_MainHand);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_OffHand);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Widget_Inventory);

	// Ability
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Crouch);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Death);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Knockback);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Stun);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Check);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Active);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint_Check);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint_Active);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChangeEquip);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Skill);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Throw);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Drink);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Block);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Active);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Object);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Widget_Inventory);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HitReact);

	// Status
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouch);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Jump);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Knockback);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stun);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Attack);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Skill);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Throw);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Block);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ChangeEquip);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS_Bow);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS_Ready);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS_Throw);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dash);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Sprint);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Succeeded);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Failed);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Interact);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_HitReact);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_RejectHitReact);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_StaminaRecoveryBlock);

	// Gameplay Event
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Begin);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Tick);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_End);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Spell);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Play);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Trace);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_CameraShake);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ChangeEquip);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Knockback);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Stun);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_HitReact);

	// Cheat
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	// Movement
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	// Message
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Notification);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Notice);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Progress);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_MyInventory);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_OtherInventory);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_MyEquipment);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_OtherEquipment);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HUD_Spell_Input);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HUD_Spell_Progress_Construct);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HUD_Spell_Progress_Refresh);

	// SetByCaller
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseDamage);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseHealth);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseStamina);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingDamage);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingHealth);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingStamina);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeed);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeedPercent);
	LYRAGAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Resourcefulness);

	// GameplayCue
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Attack);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Impact);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Overlay);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Loop);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Success);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Fail);

	// Cooldown
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Jump);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dash);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Statue);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Sprint);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_1);

	// GamePhase
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_PreGame);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_Game);
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_PostGame);

	// HUD
	LYRAGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Slot_Reticle);

	LYRAGAME_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	LYRAGAME_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	LYRAGAME_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
};
